// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtPnqZyYF8qb1-SvDDhVJdTyPwgFQ4E8',
    appId: '1:909777459549:web:1a8210f3856d2edbd670b4',
    messagingSenderId: '909777459549',
    projectId: 'easy-stor3',
    authDomain: 'easy-stor3.firebaseapp.com',
    storageBucket: 'easy-stor3.appspot.com',
    measurementId: 'G-VMQWY0RW9B',
    databaseURL: '',
    androidClientId: '',
    appGroupId: '',
    deepLinkURLScheme: '',
    iosBundleId: '',
    iosClientId: '',
    trackingId: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZobd-fDXxkV36HO90qdOUAiVLNJk2SQ',
    appId: '1:909777459549:android:52401b0d57ca079dd670b4',
    messagingSenderId: '909777459549',
    projectId: 'easy-stor3',
    storageBucket: 'easy-stor3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWwmIytggQWKGKiawXrWvOeO8_rGTqg0k',
    appId: '1:909777459549:ios:9db46ab873764d62d670b4',
    messagingSenderId: '909777459549',
    projectId: 'easy-stor3',
    storageBucket: 'easy-stor3.appspot.com',
    iosBundleId: 'com.oa.easyStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWwmIytggQWKGKiawXrWvOeO8_rGTqg0k',
    appId: '1:909777459549:ios:9db46ab873764d62d670b4',
    messagingSenderId: '909777459549',
    projectId: 'easy-stor3',
    storageBucket: 'easy-stor3.appspot.com',
    iosBundleId: 'com.oa.easyStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHtPnqZyYF8qb1-SvDDhVJdTyPwgFQ4E8',
    appId: '1:909777459549:web:9a27df72c13df65ad670b4',
    messagingSenderId: '909777459549',
    projectId: 'easy-stor3',
    authDomain: 'easy-stor3.firebaseapp.com',
    storageBucket: 'easy-stor3.appspot.com',
    measurementId: 'G-QCCTE3X1RP',
  );
}
